services:
  api:
    volumes:
      - ./app:/app/app
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000  --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - catalog_service_network
    depends_on:
      - pgsql

  pgsql:
    image: postgres:14.7-alpine
    command: [ "postgres", "-c", "max_connections=500" ]
    volumes:
      - ./tools/pgsql/service_folders/data/:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - catalog_service_network

  pgadmin:
    image: dpage/pgadmin4:7
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - catalog_service_network
    depends_on:
      - pgsql

networks:
  catalog_service_network:
    driver: bridge
