services:
  api:
    volumes:
      - ./app:/app/app
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./logging.conf:/app/logging.conf
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000  --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - catalog_service_network
    depends_on:
      - pgsql